name: nxt_home
description: "nxt.home - Find shelter, food, and job opportunities in San Francisco."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # HTTP Requests
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # State Management
  provider: ^6.1.1
  
  # Maps
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.3+1
  
  # Permissions
  permission_handler: ^11.2.0
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Web Scraping
  html: ^0.15.4
  
  # JSON Parsing
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true